(cl:defpackage custom_msgs-srv
  (:use )
  (:export
   "ACTIONSRV"
   "<ACTIONSRV-REQUEST>"
   "ACTIONSRV-REQUEST"
   "<ACTIONSRV-RESPONSE>"
   "ACTIONSRV-RESPONSE"
   "IMAGESANDBOXESSRV"
   "<IMAGESANDBOXESSRV-REQUEST>"
   "IMAGESANDBOXESSRV-REQUEST"
   "<IMAGESANDBOXESSRV-RESPONSE>"
   "IMAGESANDBOXESSRV-RESPONSE"
  ))

