// Generated by gencpp from file custom_msgs/ActionSrv.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_ACTIONSRV_H
#define CUSTOM_MSGS_MESSAGE_ACTIONSRV_H

#include <ros/service_traits.h>


#include <custom_msgs/ActionSrvRequest.h>
#include <custom_msgs/ActionSrvResponse.h>


namespace custom_msgs
{

struct ActionSrv
{

typedef ActionSrvRequest Request;
typedef ActionSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ActionSrv
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::ActionSrv > {
  static const char* value()
  {
    return "bc83a7ef89bbba9a6fa9c799fab90d6c";
  }

  static const char* value(const ::custom_msgs::ActionSrv&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::ActionSrv > {
  static const char* value()
  {
    return "custom_msgs/ActionSrv";
  }

  static const char* value(const ::custom_msgs::ActionSrv&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::ActionSrvRequest> should match 
// service_traits::MD5Sum< ::custom_msgs::ActionSrv > 
template<>
struct MD5Sum< ::custom_msgs::ActionSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::ActionSrv >::value();
  }
  static const char* value(const ::custom_msgs::ActionSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::ActionSrvRequest> should match 
// service_traits::DataType< ::custom_msgs::ActionSrv > 
template<>
struct DataType< ::custom_msgs::ActionSrvRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::ActionSrv >::value();
  }
  static const char* value(const ::custom_msgs::ActionSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::ActionSrvResponse> should match 
// service_traits::MD5Sum< ::custom_msgs::ActionSrv > 
template<>
struct MD5Sum< ::custom_msgs::ActionSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::ActionSrv >::value();
  }
  static const char* value(const ::custom_msgs::ActionSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::ActionSrvResponse> should match 
// service_traits::DataType< ::custom_msgs::ActionSrv > 
template<>
struct DataType< ::custom_msgs::ActionSrvResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::ActionSrv >::value();
  }
  static const char* value(const ::custom_msgs::ActionSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_ACTIONSRV_H
