// Generated by gencpp from file custom_msgs/Box.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_BOX_H
#define CUSTOM_MSGS_MESSAGE_BOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct Box_
{
  typedef Box_<ContainerAllocator> Type;

  Box_()
    : left(0.0)
    , top(0.0)
    , right(0.0)
    , bottom(0.0)
    , id()  {
    }
  Box_(const ContainerAllocator& _alloc)
    : left(0.0)
    , top(0.0)
    , right(0.0)
    , bottom(0.0)
    , id(_alloc)  {
  (void)_alloc;
    }



   typedef float _left_type;
  _left_type left;

   typedef float _top_type;
  _top_type top;

   typedef float _right_type;
  _right_type right;

   typedef float _bottom_type;
  _bottom_type bottom;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::custom_msgs::Box_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::Box_<ContainerAllocator> const> ConstPtr;

}; // struct Box_

typedef ::custom_msgs::Box_<std::allocator<void> > Box;

typedef boost::shared_ptr< ::custom_msgs::Box > BoxPtr;
typedef boost::shared_ptr< ::custom_msgs::Box const> BoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::Box_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::Box_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/home/greg/trobo_cpp/src/common_msgs/geometry_msgs/msg'], 'sensor_msgs': ['/home/greg/trobo_cpp/src/common_msgs/sensor_msgs/msg'], 'custom_msgs': ['/home/greg/trobo_cpp/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Box_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Box_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Box_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Box_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Box_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Box_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::Box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eedc1c5a3505cba8031ed3005ed9af89";
  }

  static const char* value(const ::custom_msgs::Box_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeedc1c5a3505cba8ULL;
  static const uint64_t static_value2 = 0x031ed3005ed9af89ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::Box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/Box";
  }

  static const char* value(const ::custom_msgs::Box_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::Box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left\n\
float32 top\n\
float32 right\n\
float32 bottom\n\
\n\
string id\n\
# the id should not be changed from 0 except for by the object prediction algorithm\n\
";
  }

  static const char* value(const ::custom_msgs::Box_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::Box_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.top);
      stream.next(m.right);
      stream.next(m.bottom);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Box_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::Box_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::Box_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "top: ";
    Printer<float>::stream(s, indent + "  ", v.top);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
    s << indent << "bottom: ";
    Printer<float>::stream(s, indent + "  ", v.bottom);
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_BOX_H
