// Generated by gencpp from file custom_msgs/ImagesAndBoxesSrvRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_IMAGESANDBOXESSRVREQUEST_H
#define CUSTOM_MSGS_MESSAGE_IMAGESANDBOXESSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct ImagesAndBoxesSrvRequest_
{
  typedef ImagesAndBoxesSrvRequest_<ContainerAllocator> Type;

  ImagesAndBoxesSrvRequest_()
    : skips(0)  {
    }
  ImagesAndBoxesSrvRequest_(const ContainerAllocator& _alloc)
    : skips(0)  {
  (void)_alloc;
    }



   typedef uint8_t _skips_type;
  _skips_type skips;





  typedef boost::shared_ptr< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImagesAndBoxesSrvRequest_

typedef ::custom_msgs::ImagesAndBoxesSrvRequest_<std::allocator<void> > ImagesAndBoxesSrvRequest;

typedef boost::shared_ptr< ::custom_msgs::ImagesAndBoxesSrvRequest > ImagesAndBoxesSrvRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::ImagesAndBoxesSrvRequest const> ImagesAndBoxesSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/home/greg/trobo_cpp/src/common_msgs/geometry_msgs/msg'], 'sensor_msgs': ['/home/greg/trobo_cpp/src/common_msgs/sensor_msgs/msg'], 'custom_msgs': ['/home/greg/trobo_cpp/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebafede1f57eb08796f2f3bba8184954";
  }

  static const char* value(const ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xebafede1f57eb087ULL;
  static const uint64_t static_value2 = 0x96f2f3bba8184954ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/ImagesAndBoxesSrvRequest";
  }

  static const char* value(const ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 skips\n\
";
  }

  static const char* value(const ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.skips);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImagesAndBoxesSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::ImagesAndBoxesSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "skips: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.skips);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_IMAGESANDBOXESSRVREQUEST_H
