// Generated by gencpp from file custom_msgs/Action.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_ACTION_H
#define CUSTOM_MSGS_MESSAGE_ACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct Action_
{
  typedef Action_<ContainerAllocator> Type;

  Action_()
    : id(0)
    , params()  {
    }
  Action_(const ContainerAllocator& _alloc)
    : id(0)
    , params(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _params_type;
  _params_type params;





  typedef boost::shared_ptr< ::custom_msgs::Action_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::Action_<ContainerAllocator> const> ConstPtr;

}; // struct Action_

typedef ::custom_msgs::Action_<std::allocator<void> > Action;

typedef boost::shared_ptr< ::custom_msgs::Action > ActionPtr;
typedef boost::shared_ptr< ::custom_msgs::Action const> ActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::Action_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::Action_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/home/greg/trobo_cpp/src/common_msgs/geometry_msgs/msg'], 'sensor_msgs': ['/home/greg/trobo_cpp/src/common_msgs/sensor_msgs/msg'], 'custom_msgs': ['/home/greg/trobo_cpp/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Action_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Action_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12707864707374042b797df45f669e2c";
  }

  static const char* value(const ::custom_msgs::Action_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1270786470737404ULL;
  static const uint64_t static_value2 = 0x2b797df45f669e2cULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/Action";
  }

  static const char* value(const ::custom_msgs::Action_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
float32[] params\n\
\n\
# The id codes are listed below\n\
# 0 - scoop\n\
# 1 - drive (left %, right %)\n\
# 2 - stop\n\
";
  }

  static const char* value(const ::custom_msgs::Action_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::Action_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Action_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::Action_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::Action_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "params[]" << std::endl;
    for (size_t i = 0; i < v.params.size(); ++i)
    {
      s << indent << "  params[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.params[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_ACTION_H
